# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target '11_TodoeyRealm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 10_Todoey
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework'

end
